### ISSUE TITLE
Entering GHG scores/changing certain staff scores

### ISSUE THREAD

**Issue by CadyLister** [BPSTechServices/pcef-public#134]
We need to enter GHG scores for several applications that have already been scored by staff (the GHG score is also a staff scored item). If the same person goes in and enters just that one GHG score will the reports pull it in without erasing all of the other staff entered scores? We need to do this for a handful of criteria 3 staff scores as well.

**Comment by derekwmiller** [comment]
@CadyLister the form will pre-populate with existing staff scores if the same person scores it. If someone else scores it the second time (to enter the missing value), the form will not pre-populate. In the latter scenario, the second person would need to re-enter all the values. Otherwise, any missing values fall out of the report.

This is the same issue that we discussed re: more than one staff person entering staff scores.
