### ISSUE TITLE
View of scoring panel report

### ISSUE THREAD

**Issue by CadyLister** [BPSTechServices/pcef-public#161]
Display for scoring panel 
•	Don’t show the criteria that do not apply (rather than having them shaded orange)
•	Where staff scoring, would be nice to have a way that doesn’t make other panel members confused or think they missed something
•	Scoring panel review tables, make it so we can see reviewer names as we scroll down

**Comment by derekwmiller** [comment]
panels currently scheduled to meet 4/4

**Comment by CadyLister** [comment]
Derek, do you have an ETA when this will be ready to review?

**Comment by derekwmiller** [comment]
@CadyLister I'm on track for tomorrow. 
Speaking of schedules -- Can we update #239?

**Comment by CadyLister** [comment]
@derekwmiller done

**Comment by derekwmiller** [comment]
Thanks @CadyLister

**Comment by derekwmiller** [comment]
@CadyLister 80 - 90% there... likely going to drag to the morning. Progress is on dev if you want to look. We're missing the majority of scores so if you want to look, i put some fake scores on # 2540 (panel 1)

**Comment by derekwmiller** [comment]
@CadyLister 
To wrap things up:

Display for scoring panel
- Don’t show the criteria that do not apply (rather than having them shaded orange)
  - Criteria that do not apply are still orange. Removing them complete would mess with the numbering and could also be just as confusing (i.e. where is the question.... )

- Where staff scoring, would be nice to have a way that doesn’t make other panel members confused or think they missed something
  - Staff scores are now in their own table, separate from the others


- Scoring panel review tables, make it so we can see reviewer names as we scroll down
  - Doing this would force changes throughout the page layout and there's no guarantee that it would be any more readable. You can only have sticky headers with a fixed height table. That means both the table and the page would scroll (not great) and the table itself would be a fixed height (less visible rows at any given time). The compromise is hovering your cursor over a cell to see the reviewers name (image below).

![image](https://user-images.githubusercontent.com/2798800/161209964-aa1d0387-b5f5-487d-b177-f127badaa127.png)
