### ISSUE TITLE
Edits to Application text

### ISSUE THREAD

**Issue by CadyLister** [BPSTechServices/pcef-public#171]
Planning application changes in track changes here https://portlandoregongov.sharepoint.com/:w:/s/pcef/EfVvW15KIHdGsjoHRRHT5wcB3IKpu96TwZ0NlsVJeRqtKw?e=EbMpev

WCD and Standard application changes in track changes here https://portlandoregongov.sharepoint.com/:w:/s/pcef/EUEMlNmucg9MgKPQ9le00B4B9GbeOIHHgeGctt3WP01P9w?e=FgFkre

**Comment by derekwmiller** [comment]
@CadyLister I made the changes to question 1.12 on both form types. The WCD / Standard document contained a number of changes that I had already implemented, so I did not go through them one by one. If there are any new edits in there other than 1.12, you'll need to accept the edit on ones that have been implemented so that I can actually tell what's new.

**Comment by CadyLister** [comment]
Looks like there is only one minor change that still needs to be made -  edit in 1.15 WCD/Standard - I left it in track changes
There are also links in 1.3 and 1.4 in WCD/Standard and Planning that would be great to bring into the portal if possible

**Comment by derekwmiller** [comment]
Changing section 1 to section 0 means renumbering the entire application. How is this the solution? What changed that prompted this?
