### ISSUE TITLE
Allowing uploads of multiple required documents

### ISSUE THREAD

**Issue by WendyKoelfgen** [BPSTechServices/pcef-public#179]
This may not be an issue. Just noting that it appears that folks can upload as many RFP responses, budgets and financials documents as they want. I think we discussed this last year and landed on that we would use whichever was the last uploaded. Am I remembering that correctly?

**Comment by derekwmiller** [comment]
Yes -- users can upload as many as they choose. That was by design last time around.

This time around, users have the ability to remove files from their application prior to submitting the final app. So -- we could limit the RFP & Budget docs to single upload. My understanding of the financials & others is that multiple is required / sometimes necessary.

This is your call. Also your call what you do with it once it's submitted.

**Comment by CadyLister** [comment]
I think we need to leave it as is. Thanks
