### ISSUE TITLE
Application review requirements

### ISSUE THREAD

**Issue by CadyLister** [BPSTechServices/pcef-public#92]
Requirements for review function
- [x] Admin panel for staff so that we can assign applications to different folks for review
- [x] Everything related to application tied to unique identifier generated during application
- [x] Read only view to read applications (will want to hide some answers, e.g. eligibility questions) 
- [x] Reviewers ability to take notes  
- [x] Reviewers need to be able to see only the applications they are assigned
- [x] Reviewers need to be able to change their scores
- [x] Some criteria have values entered by staff, some by reviewers
- [x] Need a final score document for all applications which includes individual criteria score as well as section totals (e.g. sum of all criteria in Environmental benefits section)	
- [x] Will need fields for applicant feedback – also connected to unique identifier
- [x] Will want ability to dump all into a csv file

**Comment by WendyKoelfgen** [comment]
Requirements for review function

- [x] Admin panel for staff so that we can assign applications to different folks for review

- [x] Everything related to application tied to unique identifier generated during application

- [x] Read only view to read applications (will want to hide some answers, e.g. eligibility questions)

- [x] Reviewers ability to take notes

- [x] Reviewers need to be able to see only the applications they are assigned

- [x] Reviewers need to be able to change their scores

- [x] Some criteria have values entered by staff, some by reviewers

- [x] Need a final score document for all applications which includes individual criteria score as well as section totals (e.g. sum of all criteria in Environmental benefits section)

- [x] Will need fields for applicant feedback – also connected to unique identifier

- [x] Will want ability to dump all into a csv file

- [x] Checkbox for completion of eligibility review

- [x] Yes/no designation for eligibility review outcome

- [x] Notes field for reason for failed eligibility review

- [x] Checkbox for completion of technical review

- [x] Pass/fail/not applicable designation for technical review outcome

- [x] Notes field for failed technical review description/reason

- [x] Threshold scoring capacity needed - staff may need to "pre-score" applications to determine if they move on to scoring panels
