### ISSUE TITLE
Large grant - application portal

### ISSUE THREAD

**Issue by CadyLister** [BPSTechServices/pcef-public#93]
From June and Sam review

Section 1: Applicant eligibility 
1. In Application review, this section remains red when I answer 1.2 as yes and fill in the EIN in the second box of 1.3 and leave the first box empty. If I add an EIN to the first box, it will be green in Application review. Also, 1.3 has logic that it will only accept 9-digit numbers – I think maybe we should just write that in case folks get a red box and it’s because their EIN is wrong.
 
Section 2 
1. Hover text on question 2.5 is cut off

Section 6: Workforce…
1. I can’t get this to be green even though I filled out all of the fields… my answers:
6.1 – Yes
	6.2 – Yes
	6.3 – added in text
	6.4 – Yes
o	Changed it to this and still get red:
	6.1 – Yes
	6.2 – Yes
	6.3 – added in text
	6.4 – No
o	Changed it to this and got green:
	6.1 – No
o	I also then answered so that I could fill out Section B and then filled it out and still got red. 

Upload section

1. Got null value on upload b/c not associated with a question #, can we remove the option to have that blank? 
2. Also can we offer the ability to remove uploads after they have been added in case people make a mistake or update a doc later and want to replace?

**Comment by derekwmiller** [comment]
@WendyKoelfgen can you take a look at this form validation issue and see if you can replicate? thanks.

**Comment by WendyKoelfgen** [comment]
@derekwmiller sure. In dev or in the app?

**Comment by derekwmiller** [comment]
Either is fine

**Comment by WendyKoelfgen** [comment]
Section 1 - you do have to put something in the first EIN to get a green light. 
Section 6 - Did the same sequence and also could not get section 6 to turn green. Skipped section 2-5 (just in case that is relevant)
Null value - this happens when you have uploaded one document first. Then the question number is blank and you are able to upload a document without selecting a question number and click upload. 

Does that cover what you wanted me to check?
